# Generated by Django 3.0.7 on 2020-07-29 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_messagemodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
